export enum Title {
  AccessibilityGuidelines = 'Accessibility Guidelines',
  AccessibilityMyths = 'Accessibility Myths',
  AltText = 'Effective Alt Text',
  Aria = 'ARIA',
  Buttons = 'Buttons',
  Contact = 'Contact',
  DecorativeImages = 'Decorative Images',
  Error = 'Error',
  FormElements = 'Form elements',
  FuncitionalImages = 'Complex & Functional Images',
  Headings = 'Headings',
  Home = 'Home',
  Images = 'Images',
  InformativeImages = 'Informative Images',
  Legislation = 'Legislation',
  Links = 'Links',
  Navigation = 'Navigation',
  Thanks = 'Thanks',
  Videos = 'Videos',
  Wcag = 'WCAG',
  WcagEvolutionSummery = 'WCAG Evolution summery',
  WcagFuture = 'WCAG 3.0',
}

export enum CommonText {
  Cancel = 'Cancel',
  Close = 'Close',
  CloseDialog = 'Close Dialog',
  CloseToast = 'Close Toast',
  LegalCosts = 'Legal Costs',
  LegalCostsContent = 'Additional costs related to legal fees, fines, and settlements due to non-compliance with accessibility laws.',
  LostRevenue = 'Lost Revenue',
  LostRevenueContent = 'Missed market opportunities and estimated loss of potential revenue by not catering to the market of people with disabilities.',
  OperationalInefficiencies = 'Operational Inefficiencies',
  OperationalInefficienciesContent = 'Increase in operational costs due to higher customer service demands and inefficiencies from inaccessible system.',
  OtherCosts = 'Other Costs',
  OtherCostsContent = 'Maintenance costs and development costs for retrofitting accessibility.',
  ProgressBar = 'progress bar',
  ReputationalDamage = 'Reputational Damage',
  ReputationalDamageContent = 'Potential loss in overall company valuation due to damage to brand reputation and customer loyalty.',
}

export enum BannerTitle {
  Home = 'Accessibility is really just another word for equality',
  Wcag = 'W3Cs Web Accessibility Initiative: Tackling Online Barriers',
  Wcag3IsComing = 'WCAG 3.0 is coming',
}
